### ISSUE TITLE
Tracking issue: network metrics

### ISSUE THREAD

**Issue by nud3l** [interlay/interbtc-squid#95]
Related to: https://github.com/interlay/airflow/issues/5

I noticed that I'm starting to mirror squid functionality in airflow. That is not great because we should keep code to a minimum where possible. Since we commit to using squid, we should add endpoints for the protocol and user metrics in squid where possible and use airflow only if we need to aggregate data/ad-hoc analysis.

# Protocol

- [ ] Number of daily transactions
- [ ] TVL total and by product (bridge, lending, AMM, ...)
- [ ] Volume total and by product (chain, bridge, lending, AMM, ...)
- [ ] Revenue total and by product (chain, bridge, lending, AMM, ...)
- [ ] DAO revenue share total and by product (chain, bridge, lending, AMM, ...)
- [ ] Market cap (current and fully diluted)

# Financial

- [ ] Customer acquisition cost (CAC)
- [ ] Treasury spending
- [ ] Network runway
